### ISSUE TITLE
Add GitHub Action for Code Quality and Testing on "back"

### ISSUE THREAD

**Issue by ibrahimadlani** [ibrahimadlani/twitch-recap#5]
## Description
This task involves creating a GitHub Action workflow that will run on pull requests to `main` and `develop`, as well as on push events to `develop` and `main`. The workflow will:
- Run tests using `pytest`
- Check code quality with `pylint`
- Ensure code formatting with `black`
- Install dependencies
- Verify that test coverage is greater than 95%

## Steps

1. **Create GitHub Action Workflow**:
    - Create a directory `.github/workflows` in the root of the project if it doesn't already exist.
    - Create a workflow file `.github/workflows/code_quality.yml` with the following content:
      ```yaml
      name: Code Quality and Testing

      on:
        push:
          branches:
            - main
            - develop
        pull_request:
          branches:
            - main
            - develop

      jobs:
        test:
          runs-on: ubuntu-latest

          services:
            postgres:
              image: postgres:13
              env:
                POSTGRES_DB: your_db
                POSTGRES_USER: your_user
                POSTGRES_PASSWORD: your_password
              options: >-
                --health-cmd="pg_isready -U your_user -d your_db"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=5
              ports:
                - 5432:5432

          env:
            DATABASE: postgres
            SQL_HOST: localhost
            SQL_PORT: 5432
            POSTGRES_DB: your_db
            POSTGRES_USER: your_user
            POSTGRES_PASSWORD: your_password

          steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.11

            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r requirements-dev.txt

            - name: Run migrations
              run: |
                source venv/bin/activate
                python back/manage.py migrate

            - name: Run pytest
              run: |
                source venv/bin/activate
                pytest --cov=back --cov-fail-under=95

            - name: Run pylint
              run: |
                source venv/bin/activate
                pylint back

            - name: Run black
              run: |
                source venv/bin/activate
                black --check back

            - name: Upload coverage report
              uses: actions/upload-artifact@v2
              with:
                name: coverage-report
                path: coverage.xml

      ```

2. **Ensure Dependencies and Configuration**:
    - Make sure that `pytest`, `pylint`, `black`, and other dependencies are listed in `requirements-dev.txt`.
    - Ensure that `pytest-cov` is configured to generate a `coverage.xml` file for the test coverage report.

3. **Review and Test**:
    - Commit and push the `.github/workflows/code_quality.yml` file to the repository.
    - Open a pull request to trigger the workflow and ensure it runs as expected.
    - Verify that the workflow correctly runs `pytest`, `pylint`, and `black`, and that the test coverage is checked.

## Resources
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [pytest Documentation](https://docs.pytest.org/en/stable/)
- [pylint Documentation](https://pylint.pycqa.org/en/latest/)
- [black Documentation](https://black.readthedocs.io/en/stable/)

## Priority
- High
